# Generated by Django 5.1.6 on 2026-04-19 19:24

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=profiles.models._actor_photo_path)),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube ou Vimeo')),
                ('skills', models.TextField(blank=True, help_text='Compétences, séparées par des virgules', max_length=500)),
                ('experience', models.TextField(blank=True, max_length=3000)),
                ('available', models.BooleanField(default=False, help_text='Disponible pour auditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TroupeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=profiles.models._troupe_photo_path)),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='troupe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
