# Generated by Django 5.1.6 on 2026-04-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorprofile',
            name='available',
        ),
    ]
