# Generated by Django 5.1.6 on 2026-04-19 19:35

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profiles.models._actor_extra_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.actorprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
