# Generated by Django 5.1.6 on 2026-04-19 19:49

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_actor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troupeprofile',
            old_name='logo',
            new_name='photo',
        ),
        migrations.CreateModel(
            name='TroupePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profiles.models._troupe_extra_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('troupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.troupeprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
