# Generated by Django 5.1.6 on 2025-03-01 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offer', 'Offre'), ('demand', 'Demande')], default='offer', max_length=255)),
                ('category', models.CharField(choices=[('unpaid', 'Bénévole'), ('paid', 'Rémunéré')], default='unpaid', max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('other', 'Non-Binaire'), ('female', 'Femme'), ('male', 'Homme')], default=None, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('filled', models.BooleanField(default=False)),
                ('show_author_mail', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
