# Generated by Django 5.1.6 on 2025-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offer_moderation_alter_offer_show_author_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='section',
            field=models.CharField(choices=[('artists_groups', 'Artistes & Groupes'), ('courses_training', 'Cours & Formations'), ('calls_events', 'Appels & Événements'), ('services_equipment', 'Services & Matériel')], default='artists_groups', max_length=255),
        ),
    ]
