# Generated by Django 5.1.6 on 2026-04-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offer_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Image principale / couverture de l'annonce (optionnelle).", null=True, upload_to='offers/covers/'),
        ),
        migrations.CreateModel(
            name='OfferPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (0 = premier).")),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.offer')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
