# Generated by Django 5.1.6 on 2026-04-19 16:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_description_to_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Image principale / couverture de l'annonce (optionnelle).", null=True, upload_to=core.models._offer_cover_path),
        ),
        migrations.AlterField(
            model_name='offerphoto',
            name='image',
            field=models.ImageField(upload_to=core.models._offer_photo_path),
        ),
    ]
