# Generated by Django 5.1.6 on 2026-04-19 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_s3_organized_upload_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('search', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('offer_type', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('immediate', 'Immédiatement'), ('daily', 'Quotidiennement'), ('weekly', 'Hebdomadairement')], default='daily', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='core_alert_email_cc3d09_idx')],
            },
        ),
    ]
