# Generated by Django 5.1.6 on 2026-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='allow_messaging',
            field=models.BooleanField(default=True),
        ),
    ]
