# Generated by Django 5.1.6 on 2026-04-26 10:26

from django.db import migrations, models


def migrate_moderation_status(apps, schema_editor):
    Offer = apps.get_model('core', 'Offer')
    # Annonces avec modération texte passée → published
    Offer.objects.filter(moderation__passed=True).update(moderation_status='published')
    # Annonces sans modération ou modération échouée → under_review (already the default)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_offer_allow_messaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='moderation_status',
            field=models.CharField(choices=[('published', 'Publiée'), ('under_review', 'Sous examen'), ('rejected', 'Rejetée')], default='under_review', max_length=20),
        ),
        migrations.RunPython(migrate_moderation_status, migrations.RunPython.noop),
    ]
