# Generated by Django 5.1.6 on 2026-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='moderation_status',
            field=models.CharField(choices=[('published', 'Publiée'), ('pending', 'Vérification en cours'), ('under_review', 'Sous examen'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
    ]
