# Generated by Django 5.1.6 on 2025-06-07 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('impression_count', models.PositiveIntegerField(default=0, editable=False)),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('detail_view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('booking_click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bandeau promotionnel',
                'verbose_name_plural': 'Bandeaux promotionnels',
                'ordering': ['-created_at'],
            },
        ),
    ]
