# Generated by Django 5.1.6 on 2026-04-26 13:50

import django.db.models.deletion
from django.db import migrations, models


def set_existing_confirmed(apps, schema_editor):
    Promote = apps.get_model('promote', 'Promote')
    Promote.objects.filter(play__isnull=True).update(status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ('promote', '0001_initial'),
        ('shows', '0008_add_play_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='promote',
            name='formula',
            field=models.CharField(blank=True, choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='promote',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='shows.play'),
        ),
        migrations.AddField(
            model_name='promote',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('confirmed', 'Confirmé'), ('expired', 'Expiré')], default='pending_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='promote',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(set_existing_confirmed, migrations.RunPython.noop),
    ]
