# Generated by Django 5.1.6 on 2026-05-17 11:11

from django.db import migrations, models


def mark_existing_confirmed_as_sent(apps, schema_editor):
    Promote = apps.get_model('promote', 'Promote')
    Promote.objects.filter(status='confirmed').update(notifications_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('promote', '0002_add_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='promote',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_confirmed_as_sent, migrations.RunPython.noop),
    ]
