# Generated by Django 5.1.6 on 2026-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='offer_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
