# Generated by Django 5.1.6 on 2025-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual_status', models.CharField(choices=[('not_reviewed', 'Non révisé'), ('review_requested', 'Révision demandée par l’auteur'), ('review_passed', 'Révisé et accepté'), ('review_failed', 'Révisé et rejeté')], default='not_reviewed', max_length=32)),
            ],
        ),
    ]
