# Generated by Django 5.1.6 on 2026-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='image_reasons',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='images_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
