# Generated by Django 5.1.6 on 2026-04-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_image_moderation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationresult',
            name='manual_status',
        ),
        migrations.RemoveField(
            model_name='moderationresult',
            name='passed',
        ),
    ]
