# Generated by Django 5.1.6 on 2025-10-18 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la pièce')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Auteur')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Compagnie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genre', models.CharField(choices=[('theatre', 'Théâtre'), ('dance', 'Danse'), ('lyric', 'Lyrique'), ('circus', 'Cirque'), ('youth', 'Jeune public'), ('other', 'Autres')], max_length=20, verbose_name='Genre')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/', verbose_name='Affiche')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('year_created', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle')),
                ('name', models.CharField(max_length=255, verbose_name='Nom(s)')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='shows.play')),
            ],
            options={
                'verbose_name': 'Contributeur',
                'verbose_name_plural': 'Contributeurs',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_credits', models.IntegerField(default=0, verbose_name='Crédits restants')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédit de publication',
                'verbose_name_plural': 'Crédits de publication',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date et heure')),
                ('venue', models.CharField(max_length=255, verbose_name='Lieu')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='Tarif')),
                ('ticket_url', models.URLField(blank=True, null=True, verbose_name='Lien vers la billetterie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='shows.play')),
            ],
            options={
                'verbose_name': 'Représentation',
                'verbose_name_plural': 'Représentations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Montant (€)')),
                ('credits_purchased', models.IntegerField(verbose_name='Crédits achetés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
