# Generated by Django 5.1.6 on 2026-04-19 16:35

import shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_representation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=shows.models._play_poster_path, verbose_name='Affiche'),
        ),
    ]
