# Generated by Django 5.1.6 on 2026-04-19 16:48

import django.db.models.deletion
import shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_s3_organized_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=shows.models._play_cover_path, verbose_name='Photo de couverture'),
        ),
        migrations.CreateModel(
            name='PlayPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shows.models._play_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shows.play')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
