# Generated by Django 5.1.6 on 2026-04-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_remove_passed_manual_status'),
        ('shows', '0007_play_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='moderation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='moderation.moderationresult'),
        ),
        migrations.AddField(
            model_name='play',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'En vérification'), ('published', 'Publiée'), ('under_review', 'Sous examen'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='playmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('cancelled', 'Annulée')], default='pending', max_length=10),
        ),
    ]
